### ISSUE TITLE
Model Load error in detect.py

### ISSUE THREAD

**Issue by Muaz65** [SupreethN/Hand-CNN#1]
I downloaded the [re-trained models as per your instructions. But on executinng detect.py it fails to read the model file.

*It might look that i am using an invalid path but it's not the case*
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    model = load_model_custom(InferenceConfig())
  File "detect.py", line 63, in load_model_custom
    model.load_weights('./model/trained_model.h5', by_name=True)
  File "/Users/muazmaqbool/Downloads/Hand-CNN-master/mrcnn/model.py", line 2282, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/Users/muazmaqbool/anaconda3/envs/soccer/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/Users/muazmaqbool/anaconda3/envs/soccer/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './model/trained_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by SupreethN** [comment]
Can you change ```trained_model.h5``` to ```trained_weights.h5``` in ```model.load_weights('./model/trained_model.h5', by_name=True)```

**Comment by Muaz65** [comment]
I fixed it a while ago. Thanks a lot. Your model is a life saver.

**Comment by rlczddl** [comment]
@SupreethN I have changed Can you change trained_model.h5 to trained_weights.h5 in model.load_weights('./model/trained_model.h5', by_name=True), and now I get: 
Traceback (most recent call last):                                                                                                                                                                                                             File "detect.py", line 113, in <module>                                                                                                                                                                                                        model = load_model_custom(InferenceConfig())                                                                                                                                                                                               File "detect.py", line 63, in load_model_custom                                                                                                                                                                                                model.load_weights('./model/trained_weights.h5', by_name=True)                                                                                                                                                                             File "E:\code\python\Hand-CNN-master\mrcnn\model.py", line 2295, in load_weights                                                                                                                                                               saving.load_weights_from_hdf5_group_by_name(f, layers)                                                                                                                                                                                     File "E:\enviroment\Anaconda3\envs\keras\lib\site-packages\keras\engine\saving.py", line 1309, in load_weights_from_hdf5_group_by_name                                                                                                         ' element(s).')                                                                                                                                                                                                                          ValueError: Layer #292 (named "contextual__attention_1") expects 29 weight(s), but the saved weights have 15 element(s).
