### ISSUE TITLE
err when loading trained weights.

### ISSUE THREAD

**Issue by aoru45** [SupreethN/Hand-CNN#11]
When I load the trained model, I get the err like this:

2020-05-06 21:10:40.156211: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-05-06 21:10:40.156517: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-05-06 21:10:40.156618: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Using TensorFlow backend.
2020-05-06 21:10:41.169903: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-06 21:10:41.280627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:17:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-05-06 21:10:41.280870: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-05-06 21:10:41.281167: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
2020-05-06 21:10:41.281241: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2020-05-06 21:10:41.281304: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2020-05-06 21:10:41.281363: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-05-06 21:10:41.281426: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2020-05-06 21:10:41.283925: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-06 21:10:41.283959: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-05-06 21:10:41.284263: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-05-06 21:10:41.303529: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3450000000 Hz
2020-05-06 21:10:41.303999: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562a76d5a100 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-06 21:10:41.304069: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-06 21:10:41.616838: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562a76dc00d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-05-06 21:10:41.616993: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2020-05-06 21:10:41.617248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-06 21:10:41.617344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]
(None, None, None, 1024)
(None, None, None, 1024)
WARNING:tensorflow:From /media/Store1/xar/mrcnn/model.py:794: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Traceback (most recent call last):
  File "detect.py", line 113, in <module>
    model = load_model_custom(InferenceConfig())
  File "detect.py", line 63, in load_model_custom
    model.load_weights('./model/trained_model.h5', by_name=True)
  File "/media/Store1/xar/mrcnn/model.py", line 2295, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)
  File "/media/Store1/xar/anaconda3/envs/keras/lib/python3.7/site-packages/keras/engine/saving.py", line 1309, in load_weights_from_hdf5_group_by_name
    ' element(s).')
ValueError: Layer #292 (named "contextual__attention_1") expects 29 weight(s), but the saved weights have 15 element(s).

The err said that the weight is not consistent with the model, how can I fix it?

**Comment by aoru45** [comment]
By installing tensorflow1.4.1, I solved the problem.

**Comment by PS061188** [comment]
Hi. I am using Tensorflow 2.6.0, downgrading it to 1.4.1 will mess up everything. Is there anything else that can be done by writing or changing any lines of code?

**Comment by SupreethN** [comment]
I am not sure about this. But if you want to use PyTorch, here is a related repository: https://github.com/cvlab-stonybrook/ContactHands

**Comment by PS061188** [comment]
Thank you @SupreethN for the PyTorch repository. The work is looking promising and I will definitely try it too. However, I have used this current repository of HandCNN in my work of sign language recognition. I wanted to reproduce the detection results on my dataset for submitting paper so have to run this code anyhow.
