### ISSUE TITLE
ValueError: Error when checking : expected input_image to have shape (None, None, 3) but got array with shape (1024, 1024, 4)

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [SupreethN/Hand-CNN#16]
I'm trying to use your model for my datasets. 

When i run command `python -W ignore detect.py --image_dir ../valid_imgs/` , it produces following error: 
```
WARNING:tensorflow:From /home/ubuntu/projects/Clean_data/Hand-CNN-master/mrcnn/model.py:740: The name tf.sets.set_intersection is deprecated. Please use tf.sets.intersection instead.

WARNING:tensorflow:From /home/ubuntu/projects/Clean_data/Hand-CNN-master/mrcnn/model.py:794: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Processing image:  13671206_703416493140751_1501018506_n.jpg
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    detect(model,img_dir)
  File "detect.py", line 91, in detect
    result = model.detect([img], verbose=0)[0]
  File "/home/ubuntu/projects/Clean_data/Hand-CNN-master/mrcnn/model.py", line 2702, in detect
    self.keras_model.predict([molded_images, image_metas, anchors], verbose=0)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1782, in predict
    check_batch_axis=False)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/keras/engine/training.py", line 120, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking : expected input_image to have shape (None, None, 3) but got array with shape (1024, 1024, 4)

```

What should i do?
I use tensorflow 1.14.0 because i can't find tensorflow 1.4.0.

**Comment by SupreethN** [comment]
Sounds like you are using an image with 4 channels, possibly depth image. The input should be a 3-channeled one.
