### ISSUE TITLE
Can it run in tensorflow 2+?

### ISSUE THREAD

**Issue by aligoglos** [SupreethN/Hand-CNN#17]
I tried run `detect.py` but I got error:
My environment:
windows 10
python 3.7
tensorflow 2.3

I also changed `#import tensorflow as tf` to 
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
but nothing changed!
 error:
```
py detect.py                                                                   2020-11-05 20:10:40.841896: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
(?, ?, ?, 1024)
(?, ?, ?, 1024)
WARNING:tensorflow:From C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\util\dispatch.py:201: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
Instructions for updating:
box_ind is deprecated, use box_indices instead
Traceback (most recent call last):
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 470, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1502, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1437, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\constant_op.py", line 282, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 444, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 484, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1502, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1437, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\constant_op.py", line 282, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 444, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect.py", line 115, in <module>
    model = load_model_custom(InferenceConfig())
  File "detect.py", line 64, in load_model_custom
    model = modellib.MaskRCNN(mode="inference", config=config, model_dir='./model')
  File "D:\Artificial Intelligence\HumanDetection_Tracking\_HandDetection\Hand-CNN-master\mrcnn\model.py", line 1984, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "D:\Artificial Intelligence\HumanDetection_Tracking\_HandDetection\Hand-CNN-master\mrcnn\model.py", line 2200, in build
    fc_layers_size=config.FPN_CLASSIF_FC_LAYERS_SIZE)
  File "D:\Artificial Intelligence\HumanDetection_Tracking\_HandDetection\Hand-CNN-master\mrcnn\model.py", line 990, in fpn_classifier_graph
    mrcnn_bbox = KL.Reshape((s[1], num_classes, 4), name="mrcnn_bbox")(x)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 776, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\layers\core.py", line 540, in call
    inputs, (array_ops.shape(inputs)[0],) + self.target_shape)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\array_ops.py", line 195, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 8234, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 488, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.
```

**Comment by SupreethN** [comment]
I think you have to use the same version as mentioned in ```requirements.txt```.
