### ISSUE TITLE
Getting error while trying to just detect the trained model on my sample image!

### ISSUE THREAD

**Issue by PS061188** [SupreethN/Hand-CNN#9]
this is the error I am getting when everything is installed on my PC.
Please let me know what is going wrong here.
This is the error:

(tf-gpu) C:\Users\HP\Desktop\Hand-CNN-master>python -W ignore detect.py --image_dir /images/
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\HP\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
(None, None, None, 1024)
2020-04-24 23:52:51.501368: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-04-24 23:52:51.594244: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
totalMemory: 3.00GiB freeMemory: 2.43GiB
2020-04-24 23:52:51.600115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-04-24 23:52:51.955197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-24 23:52:51.958958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2020-04-24 23:52:51.961852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2020-04-24 23:52:51.965361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2116 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
(None, None, None, 1024)
WARNING:tensorflow:From C:\Users\HP\Desktop\Hand-CNN-master\mrcnn\model.py:794: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "detect.py", line 113, in <module>
    model = load_model_custom(InferenceConfig())
  File "detect.py", line 63, in load_model_custom
    model.load_weights('./model/trained_model.h5', by_name=True)
  File "C:\Users\HP\Desktop\Hand-CNN-master\mrcnn\model.py", line 2280, in load_weights
    f = h5py.File(filepath, mode='r')
  File "C:\Users\HP\Anaconda3\envs\tf-gpu\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\HP\Anaconda3\envs\tf-gpu\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './model/trained_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by SupreethN** [comment]
Can you change ```trained_model.h5``` to ```trained_weights.h5``` in ```model.load_weights('./model/trained_model.h5', by_name=True)``` ?

**Comment by PS061188** [comment]
Hey, Thanks for the fast response. Your code is detecting the hand perfectly now. Thanks for making this available for the whole research community.
